# Generated by Django 3.2.16 on 2022-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
